eureka-server: http://localhost:8000

spring:
  application:
    name: gateway
    
server:
  port: 88

eureka:
  client:
    service-url:
      defaultZone: ${eureka-server}/eureka/
      
logging:
  config: classpath:log4j2.xml