eureka-server: http://172.16.200.53:8000

spring:
  application:
    name: gateway
  main:
    allow-bean-definition-overriding: true 
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
            - GET
            - POST
            - OPTION

server:
  port: 88

eureka:
  client:
    service-url:
      defaultZone: ${eureka-server}/eureka/
      
logging:
  config: classpath:log4j2.xml