eureka-server: http://127.0.0.1:8000

spring:
  application:
    name: gateway
  main:
    allow-bean-definition-overriding: true 
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
            - GET
            - POST
            - OPTION

server:
  port: 88

eureka:
  instance:
      prefer-ip-address: true
      instance-id: ${spring.cloud.client.ip-address}:${server.port}
      lease-renewal-interval-in-seconds: 1 # 续约更新时间间隔(秒)
      lease-expiration-duration-in-seconds: 2 # 续约到期时间
  client:
    service-url:
      defaultZone: ${eureka-server}/eureka/
    healthcheck:
      enabled: true # 开启健康检查
      
logging:
  config: classpath:log4j2.xml