spring:
  application:
    name: gateway
    
server:
  port: 88

eureka:
  client:
    service-url:
      defaultZone: http://192.168.5.20:8080/eureka/eureka/
      
logging:
  config: classpath:log4j2.xml