gateway-server: http://localhost:88
eureka-server: http://localhost:8000

server:
  port: 8102

spring:
  application:
    name: baseser
  #bus
  rabbitmq:
    host: 172.16.200.12
    port: 31430
    username: admin
    password: qwe123-=

  activiti:
    database-schema-update: true
    history-level: full
    db-history-used: true

  datasource:
    url: jdbc:mysql://172.16.200.12:30686/baseser?characterEncoding=utf8&allowMultiQueries=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: qwe123-=
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource


eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka-server}/eureka/

#超时时间设置
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

logging:
  config: classpath:log4j2.xml

security:
  oauth2:
    client:
      client-id: client1
      client-secret: 111111
      access-token-uri: ${gateway-server}/oauth/token
      user-authorization-uri: ${gateway-server}/oauth/authorize
      grant-type: client_credentials
    resource:
      user-info-uri: ${gateway-server}/api/oauth2/user
      prefer-token-info: false
    #resource:
    #  jwt:
    #    key-uri: ${oauth2-server}/oauth/token_key