#网关
gateway-server: http://127.0.0.1:88
#注册中心
eureka-server: http://127.0.0.1:8000
#rabbitmq
rabbitmq-host: 172.16.200.53
rabbitmq-port: 5672
rabbitmq-username: admin
rabbitmq-password: qwe123-=
#记得修改数据源

#端口          
server:
  port: 8106

spring:
  application:
    name: sysservice
    #bus
  rabbitmq:
    host: ${rabbitmq-host}
    port: ${rabbitmq-port}
    username: ${rabbitmq-username}
    password: ${rabbitmq-password}
  shardingsphere:
    datasource:
      names:  system,sysservice-0,sysservice-1,sysservice-2,project-0,project-1,project-2,lre-project-0,lre-project-1,lre-project-2
      system:
        type: com.zaxxer.hikari.HikariDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        jdbcUrl: jdbc:mysql://172.16.200.53:3306/system?characterEncoding=utf8&allowMultiQueries=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: qwe123-=
      sysservice-0:
        type: com.zaxxer.hikari.HikariDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        jdbcUrl: jdbc:mysql://172.16.200.53:3306/sysservice-0?characterEncoding=utf8&allowMultiQueries=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: qwe123-=
      sysservice-1:
        type: com.zaxxer.hikari.HikariDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        jdbcUrl: jdbc:mysql://172.16.200.53:3306/sysservice-1?characterEncoding=utf8&allowMultiQueries=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: qwe123-=
      sysservice-2:
        type: com.zaxxer.hikari.HikariDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        jdbcUrl: jdbc:mysql://172.16.200.53:3306/sysservice-2?characterEncoding=utf8&allowMultiQueries=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: qwe123-=
      project-0:
        type: com.zaxxer.hikari.HikariDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        jdbcUrl: jdbc:mysql://172.16.200.53:3306/project-0?characterEncoding=utf8&allowMultiQueries=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: qwe123-=
      project-1:
        type: com.zaxxer.hikari.HikariDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        jdbcUrl: jdbc:mysql://172.16.200.53:3306/project-1?characterEncoding=utf8&allowMultiQueries=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: qwe123-=
      project-2:
        type: com.zaxxer.hikari.HikariDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        jdbcUrl: jdbc:mysql://172.16.200.53:3306/project-2?characterEncoding=utf8&allowMultiQueries=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: qwe123-=  
      lre-project-0:
        type: com.zaxxer.hikari.HikariDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        jdbcUrl: jdbc:mysql://172.16.200.53:3306/lre-project-0?characterEncoding=utf8&allowMultiQueries=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: qwe123-=
      lre-project-1:
        type: com.zaxxer.hikari.HikariDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        jdbcUrl: jdbc:mysql://172.16.200.53:3306/lre-project-1?characterEncoding=utf8&allowMultiQueries=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: qwe123-=
      lre-project-2:
        type: com.zaxxer.hikari.HikariDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        jdbcUrl: jdbc:mysql://172.16.200.53:3306/lre-project-2?characterEncoding=utf8&allowMultiQueries=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: qwe123-=  
    sharding:
        broadcastTables:
        - sys_dict
        bindingTables:
        - sys_file,sys_file_relation,sys_log,sys_message
        tables:
          sys_file:
            actualDataNodes: sysservice-${0..2}.sys_file_${0..3}
            databaseStrategy:
              inline:
                shardingColumn: customer_id
                algorithmExpression: sysservice-${customer_id % 3}
            tableStrategy: 
                inline:
                  shardingColumn: customer_id
                  algorithmExpression: sys_file_${customer_id % 4}
          sys_file_relation:
            actualDataNodes: sysservice-${0..2}.sys_file_relation_${0..3}
            databaseStrategy:
              inline:
                shardingColumn: customer_id
                algorithmExpression: sysservice-${customer_id % 3}
            tableStrategy: 
                inline:
                  shardingColumn: customer_id
                  algorithmExpression: sys_file_relation_${customer_id % 4}
          sys_log:
            actualDataNodes: sysservice-${0..2}.sys_log_${0..3}
            databaseStrategy:
              inline:
                shardingColumn: customer_id
                algorithmExpression: sysservice-${customer_id % 3}
            tableStrategy: 
                inline:
                  shardingColumn: customer_id
                  algorithmExpression: sys_log_${customer_id % 4}
          sys_message:
            actualDataNodes: sysservice-${0..2}.sys_message_${0..3}
            databaseStrategy:
              inline:
                shardingColumn: customer_id
                algorithmExpression: sysservice-${customer_id % 3}
            tableStrategy: 
                inline:
                  shardingColumn: customer_id
                  algorithmExpression: sys_message_${customer_id % 4}
    props:
      sql:
        #生产环境关闭
        show: true


#注册中心  
eureka:
  instance:
      prefer-ip-address: true
      instance-id: ${spring.cloud.client.ip-address}:${server.port}
      lease-renewal-interval-in-seconds: 1 # 续约更新时间间隔(秒)
      lease-expiration-duration-in-seconds: 2 # 续约到期时间
  client:
    service-url:
      defaultZone: ${eureka-server}/eureka/
    healthcheck:
      enabled: true # 开启健康检查
#日志      
logging:
  config: classpath:log4j2.xml

#mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml,classpath:mapper/*/*.xml,classpath:mapper/*/*/*.xml
  type-aliases-package: com.sdstc.*.model
  configuration:
    #当查询数据为空时字段返回为null，不加这个查询数据为空时，字段将被隐藏
    call-setters-on-nulls: true

#超时时间设置
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
               
#oauth2配置信息
security:
  oauth2:
    client:
      client-id: client1
      client-secret: 111111
      access-token-uri: ${gateway-server}/oauth/token
      user-authorization-uri: ${gateway-server}/oauth/authorize
    resource:
      user-info-uri: ${gateway-server}/api/oauth2/user
      prefer-token-info: false
    #resource:
    #  jwt:
    #    key-uri: ${oauth2-server}/oauth/token_key