gateway-server: http://localhost:88
eureka-server: http://localhost:8000

#端口          
server:
  port: 8101

spring:
  application:
    name: system
    #bus
  rabbitmq:
    host: 172.16.200.12
    port: 31430
    username: admin
    password: qwe123-=
  shardingsphere:
    datasource:
      names: order,system,project,product
      order:
        type: com.zaxxer.hikari.HikariDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        jdbcUrl: jdbc:mysql://172.16.200.12:30686/order?characterEncoding=utf8&allowMultiQueries=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: qwe123-=
      system:
        type: com.zaxxer.hikari.HikariDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        jdbcUrl: jdbc:mysql://172.16.200.12:30686/system?characterEncoding=utf8&allowMultiQueries=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: qwe123-=        
      project:
        type: com.zaxxer.hikari.HikariDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        jdbcUrl: jdbc:mysql://172.16.200.12:30686/project?characterEncoding=utf8&allowMultiQueries=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: qwe123-=
      product:
        type: com.zaxxer.hikari.HikariDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        jdbcUrl: jdbc:mysql://172.16.200.12:30686/product?characterEncoding=utf8&allowMultiQueries=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: qwe123-=
    sharding:
        defaultDataSourceName: system
        broadcastTables: #广播表
        - pub_dict
        - pub_file
        - pub_file_relation
        - sys_user
        - sys_customer
    props:
      sql:
        show: true


#注册中心  
eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka-server}/eureka
#日志      
logging:
  config: classpath:log4j2.xml

#mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml,classpath:mapper/*/*.xml,classpath:mapper/*/*/*.xml
  type-aliases-package: com.sdstc.*.model
  configuration:
    #当查询数据为空时字段返回为null，不加这个查询数据为空时，字段将被隐藏
    call-setters-on-nulls: true
    
#oauth2配置信息
security:
  oauth2:
    client:
      client-id: client1
      client-secret: 111111
      access-token-uri: ${gateway-server}/oauth/token
      user-authorization-uri: ${gateway-server}/oauth/authorize
    resource:
      user-info-uri: ${gateway-server}/api/oauth2/user
      prefer-token-info: false
    #resource:
    #  jwt:
    #    key-uri: ${oauth2-server}/oauth/token_key