server:
 port: 8001

spring:
  session:
    store-type: redis
  redis:
    host: 172.16.200.99
    password: qwe123-=
    port: 32728
  datasource:
    url: jdbc:mysql://172.16.200.99:30592/system?characterEncoding=utf8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: qwe123-=
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource

mybatis:
  mapper-locations: classpath:mapper/*.xml,classpath:mapper/*/*.xml,classpath:mapper/*/*/*.xml
  type-aliases-package: com.sdstc.*.model
  configuration:
    call-setters-on-nulls: true
    
oauth2:
  accessTokenValiditySeconds: 300
  refreshTokenValiditySeconds: 500
  signingKey: qwe123-=